### ISSUE TITLE
Usability issues with edit field in Debug Configuration area

### ISSUE THREAD

**Issue by jreineckearm** [ARM-software/vscode-cmsis-csolution#353]
**Describe the bug**
- OS and Version: Windows 11 Enterprise
- VS Code Version: 1.104.2
- Extension Version: Internal build from main
- Target Device: Alif AE722F80F55D5LS
- Other extensions you installed (and if the issue persists after disabling them):
- A clear and concise description of what the bug is.

Some usability issues with an edit field in the debug configuration area.

**To Reproduce**
1. Use the MLEK_AV_DualCore example
2. Use debugger templates from this branch https://github.com/Open-CMSIS-Pack/debug-adapter-registry/tree/jlink-debug-configs

3. Click into the Clock edit field (at the end)
4. Keeping a key pressed down, new characters can be added very slowly, this includes behavior of backspace. Arrow keys seem fine
5. Add a character in the middle of the existing string => cursor jumps to end of line after adding the character
6. Click at beginning of field, delete first character by pressing delete key => cursor jumps to end of line after adding the character
7. Double-click on string to select all, press delete => text gets removed, but then (I believe) the default is filled in when I would like to enter my own value
8. Same as above happens when you delete the string by removing character by character with backspace.
9. Once I saw `[Object Object]` filled in after removing the string. But couldn't reproduce anymore.

10. Nit: would be nice to be able to use Ctrl+Z/Ctrl+Y for undo/redo

11. Edit field input should be trimmed before writing to files. At the moment, it adds for example trailing spaces which will create a string in quotes which upsets schema checks.

**Expected behavior**

**Code sample and logs**
- Code sample
- `tasks.json`

**Screenshots**

**Additional context**

**Comment by arneschmid** [comment]
Can't reproduce the issues in latest main build.

> 10. Nit: would be nice to be able to use Ctrl+Z/Ctrl+Y for undo/redo

Not planned yet and would require using a different type of base editor.

> Edit field input should be trimmed before writing to files. At the moment, it adds for example trailing spaces which will create a string in quotes which upsets schema checks.

should have been fixed in https://github.com/Open-CMSIS-Pack/debug-adapter-registry/pull/44 by using the number field type for the properties being a number. New scaling factor replaces there the requirement of a unit.

**Comment by jreineckearm** [comment]
All problems still exist in build 1.60.1-96-g8b8a6c3:
* I changed `clock` to type `number`. Things behave well.
* I added a new `string` type setting (see below) which I can't change to `number`. All problems outlined above show up again for the edit field that is of type `string`. The `clock` edit field of type `number` still behaves well.

Add the following to an entry in `debug-adapters.yml`.
```
          - name: My String Setting
            description: To test string settings
            yml-node: my-string
            type: string
            default: "My Default String"
```

Maybe it's an host specific problem? I am working on Windows.
